release:
  github:
    owner: Matt-Gleich
    name: Simultaneous-Updates
  prerelease: auto
before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
brews:
  - tap:
      owner: Matt-Gleich
      name: homebrew-taps
    folder: Formula
    homepage: 'https://mattglei.ch'
    description: '🏎 One command to update everything'
    commit_author:
      name: Matt-Gleich
      email: matthewgleich@gmail.com
